---
title: "compareAnnotations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Expression

```{r}
library(tidyverse)

sp1 <- "Dwil"
sp2 <- "Dwilv2"

flybExp <- read_tsv("../analysis/expression/flybase_kal_exp.tsv.gz") 
dwv2Exp <- read_tsv("../analysis/expression/dwilv2_kal_exp.tsv.gz")

table(rowSums(flybExp[, -1] > 0.5) > 3 )
table(rowSums(dwv2Exp[, -1] > 0.5) > 3 )

table(flybExp$target_id %in% dwv2Exp$target_id)
table(dwv2Exp$target_id %in% flybExp$target_id)

expressionList <- list()
bothExp <- list()
bothExp[[sp1]] <- flybExp
bothExp[[sp2]] <- dwv2Exp


for (sp in c(sp1, sp2)) {
  binaryExp <-  rowSums(bothExp[[sp]][, -1] > 0.5) > 3
  expressionList[[sp]] <- tibble(transcript_ID = unlist(bothExp[[sp]][, 1]),
                                 expressed = binaryExp)
}
```

## Orthologues


```{r}
library(tidyverse)

sp1 <- "Dwil"
sp2 <- "Dwilv2"

dict <- read_tsv("../analysis/homology/flybase_vs_dwilv2/Dwil.dict.tsv",
                 col_names = c("protein_ID", "transcript_ID"))
ortoCounts <- read_tsv("../analysis/homology/flybase_vs_dwilv2/Orthogroups/Orthogroups.GeneCount.tsv")
unassigned <- read_tsv("../analysis/homology/flybase_vs_dwilv2/Orthogroups/Orthogroups_UnassignedGenes.tsv", 
                       guess_max = 1e6)
orthoGenes <- read_tsv("../analysis/homology/flybase_vs_dwilv2/Orthogroups/Orthogroups.tsv") %>%
  bind_rows(unassigned)



bothGenelist <- list()
for (sp in c(sp1, sp2)) {
  og <- orthoGenes %>%
  filter(!is.na(.data[[sp]]))
  bothGenelist[[sp]] <- map2(pull(og, .data[[sp]]), og$Orthogroup, function(x, y){
  spt_gs <- as.character(unlist(str_split(x, ", ")))
  data.frame(transcript_ID = spt_gs,
             OG_ID = rep(y, length(spt_gs)),
             stringsAsFactors=FALSE)
  }) %>%
  bind_rows()
}

bothGenelist[[sp1]]$transcript_ID <- dict$transcript_ID[
  match(bothGenelist[[sp1]]$transcript_ID, dict$protein_ID)]

sharedOGs <- filter(ortoCounts, .data[[sp1]] > 0, .data[[sp2]] > 0)

for (sp in c(sp1, sp2)) {
  bothGenelist[[sp]][, "w_counter"] <- 
  ifelse(bothGenelist[[sp]]$OG_ID %in% sharedOGs$Orthogroup,
         TRUE, FALSE)
}

otherSps <- colnames(ortoCounts)[!colnames(ortoCounts) %in%
                                    c(sp1, sp2,
                                      "Total", "Orthogroup")]

for (sp in c(sp1, sp2)) {
  for (otherSp in otherSps){
    inOtherSp <- filter(ortoCounts, .data[[sp]] > 0,
                        .data[[otherSp]] > 0)

    bothGenelist[[sp]][, paste0(otherSp, "_homolog")] <- 
  ifelse(bothGenelist[[sp]]$OG_ID %in% inOtherSp$Orthogroup,
         TRUE, FALSE)
  }
}


```

```{r add binary expression}

for (sp in c(sp1, sp2)) {
  bothGenelist[[sp]][, "expressed"] <- 
    expressionList[[sp]]$expressed[
      match(bothGenelist[[sp]]$transcript_ID,
            expressionList[[sp]]$transcript_ID)]
}

```


```{r summarise }

numberOfHomologs <- tibble(species = character(),
                           hasCounterpart = logical(),
                           isExpressed = logical(),
                           homologyTo = character(),
                           nGenesWithHomology = integer(),
                           nGenesWoHomology = integer())

for (sp in c(sp1, sp2)) {
  for (isNotExpressed in c(T, F)) {
    for (hasNoCounterpart in c(T, F)) {
      
      numSpWithHomologs <- filter(bothGenelist[[sp]],
                                  xor(w_counter, hasNoCounterpart)) %>%
        filter(xor(expressed, isNotExpressed)) %>%
        mutate(numSpWithHomologs = rowSums(
          select(., all_of(paste0(otherSps, "_homolog"))))) %>%
        pull(numSpWithHomologs)
      
      nGenesWithHomologs <- sum(numSpWithHomologs > 0)
      nGenesWoHomologs <- sum(numSpWithHomologs == 0) 
      
      rowNumOfHomologs <- tibble(species = sp,
                                 hasCounterpart = !hasNoCounterpart,
                                 isExpressed = !isNotExpressed,
                                 homologyTo = "anyOther",
                                 nGenesWithHomology = nGenesWithHomologs,
                                 nGenesWoHomology = nGenesWoHomologs)
      numberOfHomologs <- bind_rows(numberOfHomologs, rowNumOfHomologs)
      
      for (otherSp in otherSps){
        homologyToOtherSp <- filter(bothGenelist[[sp]],
                                    xor(w_counter, hasNoCounterpart))  %>%
          filter(xor(expressed, isNotExpressed)) %>%
          pull(.data[[paste0(otherSp, "_homolog")]])
        nGenesWithHomologs <- sum(homologyToOtherSp)
        nGenesWoHomologs <- sum(!homologyToOtherSp) 
        rowNumOfHomologs <- tibble(species = sp,
                                   hasCounterpart = !hasNoCounterpart,
                                   isExpressed = !isNotExpressed,
                                   homologyTo = otherSp,
                                   nGenesWithHomology = nGenesWithHomologs,
                                   nGenesWoHomology = nGenesWoHomologs)
        numberOfHomologs <- bind_rows(numberOfHomologs, rowNumOfHomologs)
      }
    }
  }
}


filter(numberOfHomologs, species == sp1, !isExpressed,
       !hasCounterpart,
       homologyTo == "anyOther") %>% 
  mutate(nGenes = nGenesWithHomology + nGenesWoHomology) %>%
  summarise(sum(nGenes))

# write_tsv(numberOfHomologs, "../report/tables/summary_of_expressed_genes_with_counterpart_and_homology.tsv")

```

```{r fill Jose formated table}
one2oneOgroups <- filter(ortoCounts, Dwil == 1,
                         Dwilv2 == 1) %>%
  pull(Orthogroup)


one2onebothGenelist <- list()
for (sp in c(sp1, sp2)) {
  one2onebothGenelist[[sp]] <- bothGenelist[[sp]][bothGenelist[[sp]]$OG_ID %in%
    one2oneOgroups,]
}

bothGenelist <- one2onebothGenelist

filter(numberOfHomologs, species == sp1,
       !hasCounterpart,
       homologyTo == "anyOther") %>% 
  mutate(nGenes = nGenesWithHomology + nGenesWoHomology) %>%
  summarise(sum(nGenes))

newVec <- integer()
for (cond in c("Dmel", "Dpse", "Dsim", "Dyak", "Dbus", "anyOther")){
  numG <- filter(numberOfHomologs, species == sp2,
       homologyTo == cond) %>% 
  mutate(nGenes = nGenesWithHomology) %>%
  summarise(sum(nGenes)) 
  
  newVec <- c(newVec, unlist(numG))
}
paste(newVec, collapse = " ")
```


```{r tabulate counts}

filter(ortoCounts, Dwil > 0 |  Dwilv2 > 0) %>%
  count(Dwil, Dwilv2) %>%
  arrange(Dwilv2) %>%
  pivot_wider(id_cols = Dwil, names_from = Dwilv2,
              values_from = n, values_fill = 0) %>%
  arrange(Dwil) %>%
  write_tsv("../report/tables/tabulate_homolog_counts.tsv")

filter(ortoCounts, (Dwil > 0 & Dwilv2 == 0) |
         (Dwil == 0 & Dwilv2 > 0)) %>%
  count(Dwil, Dwilv2) %>% 
  summarise(totDw = sum(Dwil * n))

sum(!is.na(unassigned$Dwil)) 
sum(!is.na(unassigned$Dwilv2))
```

```{r compare lncRNA IDs}
library(tidyverse)

lnc_gffcomp <- read_tsv("/Users/pg17/Downloads/gffcmp.all_lncRNA_featuresfinal_annot.gtf.tmap")
lnids <- read_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/analysis/FEELnc/dwil_repeat_related_lncRNAs.txt",
                  col_names = "ids") %>% pull(ids)
lninfo <- read_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/analysis/FEELnc/candidate_lncRNA_classes.txt") %>%
  mutate(repeatRelated = lncRNA_transcript %in% lnids)

filter(lninfo, isBest == 1, lncRNA_transcript %in% lnc_gffcomp$ref_id) %>%
  group_by(lncRNA_gene) %>%
  summarise(n_transcripts = n_distinct(lncRNA_transcript),
            type_of_lncRNA = paste(unique(type), collapse = ","),
            repeatRel = any(repeatRelated)) %>%
  select(type_of_lncRNA, repeatRel, lncRNA_gene, n_transcripts) %>%
  write_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/report/lncRNA_classes_and_repeat_inersect.tsv")

filter(lninfo, isBest == 1, lncRNA_gene %in% lnc_gffcomp$qry_gene_id) %>%
  group_by(lncRNA_gene) %>%
  summarise(n_transcripts = n_distinct(lncRNA_transcript),
            type_of_lncRNA = paste(unique(type), collapse = ","),
            repeatRel = any(repeatRelated)) %>%
  filter(!repeatRel)


# What are the transcripts ommitted from certain gene IDs?
trWitGIDnFAnnot <- read_lines("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/analysis//classified_lncrna_transcript_ids_with_gene_ids_in_final_annot.txt") 

table(trWitGIDnFAnnot %in% lnc_gffcomp$qry_id)
discrepantLnTr <- trWitGIDnFAnnot[!trWitGIDnFAnnot %in% lnc_gffcomp$qry_id]
discrepantLnG <- filter(lninfo, isBest == 1, lncRNA_transcript %in% discrepantLnTr) %>%
  count(lncRNA_gene)
filter(lninfo, isBest == 1, lncRNA_gene %in% discrepantLnG$lncRNA_gene) %>%
  count(lncRNA_gene)
```


```{r gene ID lists for Jose}
# he asks for 
# - una lista con los ids de los 25 gene models agrupados por gene entity que estan presentes en nuestra anotacion y no en r1.05.
# - una lista con los ids de los 41 gene models agrupados por gene entity que estan presentes en r1.05 y no en nuestra anotacion.
# una lista con los 184 gene models agrupados por gene entity que estan presentes en nuestra anotacion pero que estan en un numero diferente de copias respecto a la anterior anotacion.

# Let's recreate the numbers as these are not found in numberOfHomologs variable

# Convert IDs and save
dwilDict <- read_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/analysis/dwil-all-translation-r1.05.gene2mRNA.tsv",
                     col_names = c("pID", "gID", "tID"))
dwilv2Dict <- read_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/analysis/dwilv2_nodupIDs.gene2mRNA.tsv",
                     col_names = c("gID", "tID"))



# This matches to number two
filter(ortoCounts, (Dwil == 0 & Dwilv2 > 0)) %>%
  count(Dwil, Dwilv2) %>% 
  summarise(totDw = sum(Dwilv2 * n))
# Let's get the OG ids and then the actual gene IDs
ogMissV1 <- filter(ortoCounts, (Dwil == 0 & Dwilv2 > 0)) %>% pull(Orthogroup)
ogMissV1_tbl <- filter(bothGenelist[[sp2]], OG_ID %in% ogMissV1) %>% 
  arrange(OG_ID) %>%
  mutate(gene_ID = dwilv2Dict$gID[match(transcript_ID, dwilv2Dict$tID)]) %>% 
  select(gene_ID, OG_ID)


# This matches to number two
filter(ortoCounts, (Dwil > 0 & Dwilv2 == 0)) %>%
  count(Dwil, Dwilv2) %>% 
  summarise(totDw = sum(Dwil * n))
# Let's get the OG ids and then the actual gene IDs
ogMissV2 <- filter(ortoCounts, (Dwil > 0 & Dwilv2 == 0)) %>% pull(Orthogroup)
ogMissV2_tbl <- filter(bothGenelist[[sp1]], OG_ID %in% ogMissV2) %>% 
  arrange(OG_ID) %>%
  mutate(gene_ID = dwilDict$gID[match(transcript_ID, dwilDict$tID)]) %>%
  select(gene_ID, OG_ID)


# This matches to number three
filter(ortoCounts, Dwil > 0, Dwilv2 > 0,
                    Dwil != Dwilv2) %>%
  count(Dwil, Dwilv2) %>% 
  summarise(totDw = sum(Dwilv2 * n))
# Let's get the OG ids and then the actual gene IDs
ogDiffCounts <- filter(ortoCounts, 
                       Dwil > 0, Dwilv2 > 0,
                       Dwil != Dwilv2) %>% 
  pull(Orthogroup)
ogDiffCounts_tbl <- filter(bothGenelist[[sp2]], OG_ID %in% ogDiffCounts) %>% 
  arrange(OG_ID) %>%
  mutate(gene_ID = dwilv2Dict$gID[match(transcript_ID, dwilv2Dict$tID)]) %>% 
  select(gene_ID, OG_ID)

write_tsv(ogMissV1_tbl, "/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/report/tables/ogMissV1.tsv")
write_tsv(ogMissV2_tbl, "/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/report/tables/ogMissV2.tsv")
write_tsv(ogDiffCounts_tbl, "/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/report/tables/ogiffCounts.tsv")


```


The process is
1) get individual features (transcripts)
2) translate into gene IDs
3) group back by correspondence to other annotation (OG_ID)
4) shrink into one row per OG_ID with both v1 and v2 gene IDs.

```{r get gene ID correspondence}
# Convert IDs and save
dwilDict <- read_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/analysis/dwil-all-translation-r1.05.gene2mRNA.tsv",
                     col_names = c("pID", "gID", "tID"))
dwilv2Dict <- read_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/analysis/dwilv2_nodupIDs.gene2mRNA.tsv",
                     col_names = c("gID", "tID"))

dwilDictFixMiRNA <- read_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/analysis/dwil-all-translation-r1.05.gene2mRNA.tsv",
                     col_names = c("pID", "gID", "tID"))
dwilv2DictFixMiRNA <- read_tsv("~/Documents/Investigacion/CoLab/Dwillistoni/analysis/Dwilv2_longest_iso.dict",
                     col_names = c("tID", "gID"))
dmelDict <- read_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/analysis/Dmel_genePos.tsv",
                     col_names = c("chr", "start", "end", "strand", "tID", "gID"))

og <- orthoGenes %>%
  filter(!is.na(.data[["Dmel"]]))
bothGenelist[["Dmel"]] <- map2(pull(og, .data[["Dmel"]]), og$Orthogroup, function(x, y){
  spt_gs <- as.character(unlist(str_split(x, ", ")))
  data.frame(transcript_ID = spt_gs,
             OG_ID = rep(y, length(spt_gs)),
             stringsAsFactors=FALSE)
  }) %>%
  bind_rows()

bothGenelist[["Dmel"]]$gene_ID <- dmelDict$gID[
  match(bothGenelist[["Dmel"]]$transcript_ID, dmelDict$tID)]

bothGenelist[[sp1]]$gene_ID <- dwilDict$gID[
  match(bothGenelist[[sp1]]$transcript_ID, dwilDict$tID)]

bothGenelist[[sp2]]$gene_ID <- dwilv2Dict$gID[
  match(bothGenelist[[sp2]]$transcript_ID, dwilv2Dict$tID)]

sharedOGs <- filter(ortoCounts, .data[[sp1]] > 0, .data[[sp2]] > 0)

dmel_gIDs_OGIDs <- bothGenelist[["Dmel"]] %>%
  group_by(OG_ID) %>%
  summarise(OG_ID = unique(OG_ID),
            gIDs = paste(gene_ID, collapse = ","))

v1_gIDs_OGIDs <- bothGenelist[[sp1]] %>%
  group_by(OG_ID) %>%
  summarise(OG_ID = unique(OG_ID),
            gIDs = paste(gene_ID, collapse = ","))

v2_gIDs_OGIDs <- bothGenelist[[sp2]] %>%
  group_by(OG_ID) %>%
  summarise(OG_ID = unique(OG_ID),
            gIDs = paste(gene_ID, collapse = ","))

v1_to_v2_gIDs <- full_join(v1_gIDs_OGIDs, v2_gIDs_OGIDs, by = "OG_ID",
          suffix = c(".v1", ".v2")) %>%
  mutate(oneToOne = ifelse(!grepl(",", gIDs.v1) &
                             !grepl(",", gIDs.v2) &
                             !is.na(gIDs.v1) &
                             !is.na(gIDs.v2)
                           ,
                           TRUE, FALSE))
left_join(v1_to_v2_gIDs, dmel_gIDs_OGIDs, by = "OG_ID") %>% 
  rename(Dmel_gID = gIDs) %>%
  mutate(dmel_orto = ifelse(!is.na(Dmel_gID), TRUE, FALSE)) %>%
  mutate(gIDs.v2 = ifelse(OG_ID == "OG0002250", "FBgn0219298", 
  ifelse(OG_ID == "OG0006159", "FBgn0221759", 
  ifelse(OG_ID == "OG0011183", "FBgn0279704", 
  ifelse(OG_ID == "OG0015105", "FBgn0226673", 
  ifelse(OG_ID == "OG0015100", "FBgn0218864", 
  ifelse(OG_ID == "OG0015094", "FBgn0226988", 
  ifelse(OG_ID == "OG0015092", "FBgn0227189", gIDs.v2)))))))) %>%
  write_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/report/tables/v1_to_v2_gIDs.tsv")

# Three failing OG maps
# OG0002250 FBgn0219298
# OG0006159 FBgn0221759
# OG0011183 FBgn0279704
```

```{r investigate NAs in tables for Jose} 

sharedOGs <- filter(ortoCounts, .data[[sp1]] > 0, .data[[sp2]] > 0)

dmel_tIDs_OGIDs <- bothGenelist[["Dmel"]] %>%
  group_by(OG_ID) %>%
  summarise(OG_ID = unique(OG_ID),
            tIDs = paste(transcript_ID, collapse = ","))

v1_tIDs_OGIDs <- bothGenelist[[sp1]] %>%
  group_by(OG_ID) %>%
  summarise(OG_ID = unique(OG_ID),
            tIDs = paste(transcript_ID, collapse = ","))

v2_tIDs_OGIDs <- bothGenelist[[sp2]] %>%
  group_by(OG_ID) %>%
  summarise(OG_ID = unique(OG_ID),
            tIDs = paste(transcript_ID, collapse = ","))

v1_to_v2_tIDs <- full_join(v1_tIDs_OGIDs, v2_tIDs_OGIDs, by = "OG_ID",
          suffix = c(".v1", ".v2")) %>%
  mutate(oneToOne = ifelse(!grepl(",", tIDs.v1) &
                             !grepl(",", tIDs.v2) &
                             !is.na(tIDs.v1) &
                             !is.na(tIDs.v2),
                           TRUE, FALSE))
left_join(v1_to_v2_tIDs, dmel_tIDs_OGIDs, by = "OG_ID") %>% 
  rename(Dmel_tID = tIDs) %>% View
  # write_tsv("/Users/pg17/Documents/Investigacion/CoLab/Dwillistoni/report/tables/v1_to_v2_gIDs.tsv")
```

